/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiCreateNodeRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5353141457947934005L;
    private String appEUI;
    private String appKey;
    private String channelListID;
    private String devEUI;
    private Integer rx1DROffset;
    private Integer rx2DR;
    private Integer rxDelay;
    private ApiRXWindowEnum rxWindow = ApiRXWindowEnum.RX1;
    /** GETTER
     * hex encoded AppEUI
     */
    @JsonGetter("appEUI")
    public String getAppEUI ( ) { 
        return this.appEUI;
    }
    
    /** SETTER
     * hex encoded AppEUI
     */
    @JsonSetter("appEUI")
    public void setAppEUI (String value) { 
        this.appEUI = value;
    }
 
    /** GETTER
     * hex encoded AppKey
     */
    @JsonGetter("appKey")
    public String getAppKey ( ) { 
        return this.appKey;
    }
    
    /** SETTER
     * hex encoded AppKey
     */
    @JsonSetter("appKey")
    public void setAppKey (String value) { 
        this.appKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("channelListID")
    public String getChannelListID ( ) { 
        return this.channelListID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("channelListID")
    public void setChannelListID (String value) { 
        this.channelListID = value;
    }
 
    /** GETTER
     * hex encoded DevEUI
     */
    @JsonGetter("devEUI")
    public String getDevEUI ( ) { 
        return this.devEUI;
    }
    
    /** SETTER
     * hex encoded DevEUI
     */
    @JsonSetter("devEUI")
    public void setDevEUI (String value) { 
        this.devEUI = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rx1DROffset")
    public Integer getRx1DROffset ( ) { 
        return this.rx1DROffset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rx1DROffset")
    public void setRx1DROffset (Integer value) { 
        this.rx1DROffset = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rx2DR")
    public Integer getRx2DR ( ) { 
        return this.rx2DR;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rx2DR")
    public void setRx2DR (Integer value) { 
        this.rx2DR = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rxDelay")
    public Integer getRxDelay ( ) { 
        return this.rxDelay;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rxDelay")
    public void setRxDelay (Integer value) { 
        this.rxDelay = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rxWindow")
    public ApiRXWindowEnum getRxWindow ( ) { 
        return this.rxWindow;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rxWindow")
    public void setRxWindow (ApiRXWindowEnum value) { 
        this.rxWindow = value;
    }
 
}
 