/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateApplicationRequestBuilder {
    //the instance to build
    private ApiCreateApplicationRequest apiCreateApplicationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateApplicationRequestBuilder() {
        apiCreateApplicationRequest = new ApiCreateApplicationRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiCreateApplicationRequestBuilder appEUI(String appEUI) {
        apiCreateApplicationRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * name of the application
     */
    public ApiCreateApplicationRequestBuilder name(String name) {
        apiCreateApplicationRequest.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateApplicationRequest build() {
        return apiCreateApplicationRequest;
    }
}