/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiCreateNodeSessionRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5308570082628019494L;
    private String appEUI;
    private String appSKey;
    private List<Integer> cFList;
    private String devAddr;
    private String devEUI;
    private Integer fCntDown;
    private Integer fCntUp;
    private String nwkSKey;
    private Integer rx1DROffset;
    private Integer rx2DR;
    private Integer rxDelay;
    private ApiRXWindowEnum rxWindow = ApiRXWindowEnum.RX1;
    /** GETTER
     * hex encoded AppEUI
     */
    @JsonGetter("appEUI")
    public String getAppEUI ( ) { 
        return this.appEUI;
    }
    
    /** SETTER
     * hex encoded AppEUI
     */
    @JsonSetter("appEUI")
    public void setAppEUI (String value) { 
        this.appEUI = value;
    }
 
    /** GETTER
     * hex encoded AppSKey
     */
    @JsonGetter("appSKey")
    public String getAppSKey ( ) { 
        return this.appSKey;
    }
    
    /** SETTER
     * hex encoded AppSKey
     */
    @JsonSetter("appSKey")
    public void setAppSKey (String value) { 
        this.appSKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("cFList")
    public List<Integer> getCFList ( ) { 
        return this.cFList;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("cFList")
    public void setCFList (List<Integer> value) { 
        this.cFList = value;
    }
 
    /** GETTER
     * hex encoded DevAddr
     */
    @JsonGetter("devAddr")
    public String getDevAddr ( ) { 
        return this.devAddr;
    }
    
    /** SETTER
     * hex encoded DevAddr
     */
    @JsonSetter("devAddr")
    public void setDevAddr (String value) { 
        this.devAddr = value;
    }
 
    /** GETTER
     * hex encoded DevEUI
     */
    @JsonGetter("devEUI")
    public String getDevEUI ( ) { 
        return this.devEUI;
    }
    
    /** SETTER
     * hex encoded DevEUI
     */
    @JsonSetter("devEUI")
    public void setDevEUI (String value) { 
        this.devEUI = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fCntDown")
    public Integer getFCntDown ( ) { 
        return this.fCntDown;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fCntDown")
    public void setFCntDown (Integer value) { 
        this.fCntDown = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("fCntUp")
    public Integer getFCntUp ( ) { 
        return this.fCntUp;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("fCntUp")
    public void setFCntUp (Integer value) { 
        this.fCntUp = value;
    }
 
    /** GETTER
     * hex encoded NwkSKey
     */
    @JsonGetter("nwkSKey")
    public String getNwkSKey ( ) { 
        return this.nwkSKey;
    }
    
    /** SETTER
     * hex encoded NwkSKey
     */
    @JsonSetter("nwkSKey")
    public void setNwkSKey (String value) { 
        this.nwkSKey = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rx1DROffset")
    public Integer getRx1DROffset ( ) { 
        return this.rx1DROffset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rx1DROffset")
    public void setRx1DROffset (Integer value) { 
        this.rx1DROffset = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rx2DR")
    public Integer getRx2DR ( ) { 
        return this.rx2DR;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rx2DR")
    public void setRx2DR (Integer value) { 
        this.rx2DR = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rxDelay")
    public Integer getRxDelay ( ) { 
        return this.rxDelay;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rxDelay")
    public void setRxDelay (Integer value) { 
        this.rxDelay = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("rxWindow")
    public ApiRXWindowEnum getRxWindow ( ) { 
        return this.rxWindow;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("rxWindow")
    public void setRxWindow (ApiRXWindowEnum value) { 
        this.rxWindow = value;
    }
 
}
 