/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateChannelListResponseBuilder {
    //the instance to build
    private ApiCreateChannelListResponse apiCreateChannelListResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateChannelListResponseBuilder() {
        apiCreateChannelListResponse = new ApiCreateChannelListResponse();
    }

    public ApiCreateChannelListResponseBuilder id(String id) {
        apiCreateChannelListResponse.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateChannelListResponse build() {
        return apiCreateChannelListResponse;
    }
}