/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateNodeRequestBuilder {
    //the instance to build
    private ApiCreateNodeRequest apiCreateNodeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateNodeRequestBuilder() {
        apiCreateNodeRequest = new ApiCreateNodeRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiCreateNodeRequestBuilder appEUI(String appEUI) {
        apiCreateNodeRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppKey
     */
    public ApiCreateNodeRequestBuilder appKey(String appKey) {
        apiCreateNodeRequest.setAppKey(appKey);
        return this;
    }

    public ApiCreateNodeRequestBuilder channelListID(String channelListID) {
        apiCreateNodeRequest.setChannelListID(channelListID);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiCreateNodeRequestBuilder devEUI(String devEUI) {
        apiCreateNodeRequest.setDevEUI(devEUI);
        return this;
    }

    public ApiCreateNodeRequestBuilder rx1DROffset(Integer rx1DROffset) {
        apiCreateNodeRequest.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiCreateNodeRequestBuilder rx2DR(Integer rx2DR) {
        apiCreateNodeRequest.setRx2DR(rx2DR);
        return this;
    }

    public ApiCreateNodeRequestBuilder rxDelay(Integer rxDelay) {
        apiCreateNodeRequest.setRxDelay(rxDelay);
        return this;
    }

    public ApiCreateNodeRequestBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiCreateNodeRequest.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateNodeRequest build() {
        return apiCreateNodeRequest;
    }
}