/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateChannelResponseBuilder {
    //the instance to build
    private ApiCreateChannelResponse apiCreateChannelResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateChannelResponseBuilder() {
        apiCreateChannelResponse = new ApiCreateChannelResponse();
    }

    public ApiCreateChannelResponseBuilder id(String id) {
        apiCreateChannelResponse.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateChannelResponse build() {
        return apiCreateChannelResponse;
    }
}