/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateChannelListRequestBuilder {
    //the instance to build
    private ApiCreateChannelListRequest apiCreateChannelListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateChannelListRequestBuilder() {
        apiCreateChannelListRequest = new ApiCreateChannelListRequest();
    }

    public ApiCreateChannelListRequestBuilder name(String name) {
        apiCreateChannelListRequest.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateChannelListRequest build() {
        return apiCreateChannelListRequest;
    }
}