/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiCreateNodeSessionRequestBuilder {
    //the instance to build
    private ApiCreateNodeSessionRequest apiCreateNodeSessionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiCreateNodeSessionRequestBuilder() {
        apiCreateNodeSessionRequest = new ApiCreateNodeSessionRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiCreateNodeSessionRequestBuilder appEUI(String appEUI) {
        apiCreateNodeSessionRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppSKey
     */
    public ApiCreateNodeSessionRequestBuilder appSKey(String appSKey) {
        apiCreateNodeSessionRequest.setAppSKey(appSKey);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder cFList(List<Integer> cFList) {
        apiCreateNodeSessionRequest.setCFList(cFList);
        return this;
    }

    /**
     * hex encoded DevAddr
     */
    public ApiCreateNodeSessionRequestBuilder devAddr(String devAddr) {
        apiCreateNodeSessionRequest.setDevAddr(devAddr);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiCreateNodeSessionRequestBuilder devEUI(String devEUI) {
        apiCreateNodeSessionRequest.setDevEUI(devEUI);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder fCntDown(Integer fCntDown) {
        apiCreateNodeSessionRequest.setFCntDown(fCntDown);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder fCntUp(Integer fCntUp) {
        apiCreateNodeSessionRequest.setFCntUp(fCntUp);
        return this;
    }

    /**
     * hex encoded NwkSKey
     */
    public ApiCreateNodeSessionRequestBuilder nwkSKey(String nwkSKey) {
        apiCreateNodeSessionRequest.setNwkSKey(nwkSKey);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder rx1DROffset(Integer rx1DROffset) {
        apiCreateNodeSessionRequest.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder rx2DR(Integer rx2DR) {
        apiCreateNodeSessionRequest.setRx2DR(rx2DR);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder rxDelay(Integer rxDelay) {
        apiCreateNodeSessionRequest.setRxDelay(rxDelay);
        return this;
    }

    public ApiCreateNodeSessionRequestBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiCreateNodeSessionRequest.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiCreateNodeSessionRequest build() {
        return apiCreateNodeSessionRequest;
    }
}