/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiDeleteApplicationRequestBuilder {
    //the instance to build
    private ApiDeleteApplicationRequest apiDeleteApplicationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiDeleteApplicationRequestBuilder() {
        apiDeleteApplicationRequest = new ApiDeleteApplicationRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiDeleteApplicationRequestBuilder appEUI(String appEUI) {
        apiDeleteApplicationRequest.setAppEUI(appEUI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiDeleteApplicationRequest build() {
        return apiDeleteApplicationRequest;
    }
}