/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiDeleteChannelListRequestBuilder {
    //the instance to build
    private ApiDeleteChannelListRequest apiDeleteChannelListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiDeleteChannelListRequestBuilder() {
        apiDeleteChannelListRequest = new ApiDeleteChannelListRequest();
    }

    public ApiDeleteChannelListRequestBuilder id(String id) {
        apiDeleteChannelListRequest.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiDeleteChannelListRequest build() {
        return apiDeleteChannelListRequest;
    }
}