/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiDeleteNodeRequestBuilder {
    //the instance to build
    private ApiDeleteNodeRequest apiDeleteNodeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiDeleteNodeRequestBuilder() {
        apiDeleteNodeRequest = new ApiDeleteNodeRequest();
    }

    /**
     * hex encoded DevEUI
     */
    public ApiDeleteNodeRequestBuilder devEUI(String devEUI) {
        apiDeleteNodeRequest.setDevEUI(devEUI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiDeleteNodeRequest build() {
        return apiDeleteNodeRequest;
    }
}