/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiDeleteNodeSessionRequestBuilder {
    //the instance to build
    private ApiDeleteNodeSessionRequest apiDeleteNodeSessionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiDeleteNodeSessionRequestBuilder() {
        apiDeleteNodeSessionRequest = new ApiDeleteNodeSessionRequest();
    }

    /**
     * hex encoded DevAddr
     */
    public ApiDeleteNodeSessionRequestBuilder devAddr(String devAddr) {
        apiDeleteNodeSessionRequest.setDevAddr(devAddr);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiDeleteNodeSessionRequest build() {
        return apiDeleteNodeSessionRequest;
    }
}