/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiFlushTXPayloadQueueRequestBuilder {
    //the instance to build
    private ApiFlushTXPayloadQueueRequest apiFlushTXPayloadQueueRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiFlushTXPayloadQueueRequestBuilder() {
        apiFlushTXPayloadQueueRequest = new ApiFlushTXPayloadQueueRequest();
    }

    /**
     * hex encoded DevEUI
     */
    public ApiFlushTXPayloadQueueRequestBuilder devEUI(String devEUI) {
        apiFlushTXPayloadQueueRequest.setDevEUI(devEUI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiFlushTXPayloadQueueRequest build() {
        return apiFlushTXPayloadQueueRequest;
    }
}