/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetNodeSessionByDevEUIRequestBuilder {
    //the instance to build
    private ApiGetNodeSessionByDevEUIRequest apiGetNodeSessionByDevEUIRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetNodeSessionByDevEUIRequestBuilder() {
        apiGetNodeSessionByDevEUIRequest = new ApiGetNodeSessionByDevEUIRequest();
    }

    /**
     * hex encoded DevEUI
     */
    public ApiGetNodeSessionByDevEUIRequestBuilder devEUI(String devEUI) {
        apiGetNodeSessionByDevEUIRequest.setDevEUI(devEUI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetNodeSessionByDevEUIRequest build() {
        return apiGetNodeSessionByDevEUIRequest;
    }
}