/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetChannelResponseBuilder {
    //the instance to build
    private ApiGetChannelResponse apiGetChannelResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetChannelResponseBuilder() {
        apiGetChannelResponse = new ApiGetChannelResponse();
    }

    public ApiGetChannelResponseBuilder channel(String channel) {
        apiGetChannelResponse.setChannel(channel);
        return this;
    }

    public ApiGetChannelResponseBuilder channelListID(String channelListID) {
        apiGetChannelResponse.setChannelListID(channelListID);
        return this;
    }

    public ApiGetChannelResponseBuilder frequency(String frequency) {
        apiGetChannelResponse.setFrequency(frequency);
        return this;
    }

    public ApiGetChannelResponseBuilder id(String id) {
        apiGetChannelResponse.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetChannelResponse build() {
        return apiGetChannelResponse;
    }
}