/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetNodeResponseBuilder {
    //the instance to build
    private ApiGetNodeResponse apiGetNodeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetNodeResponseBuilder() {
        apiGetNodeResponse = new ApiGetNodeResponse();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiGetNodeResponseBuilder appEUI(String appEUI) {
        apiGetNodeResponse.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppKey
     */
    public ApiGetNodeResponseBuilder appKey(String appKey) {
        apiGetNodeResponse.setAppKey(appKey);
        return this;
    }

    public ApiGetNodeResponseBuilder channelListID(String channelListID) {
        apiGetNodeResponse.setChannelListID(channelListID);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiGetNodeResponseBuilder devEUI(String devEUI) {
        apiGetNodeResponse.setDevEUI(devEUI);
        return this;
    }

    public ApiGetNodeResponseBuilder rx1DROffset(Integer rx1DROffset) {
        apiGetNodeResponse.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiGetNodeResponseBuilder rx2DR(Integer rx2DR) {
        apiGetNodeResponse.setRx2DR(rx2DR);
        return this;
    }

    public ApiGetNodeResponseBuilder rxDelay(Integer rxDelay) {
        apiGetNodeResponse.setRxDelay(rxDelay);
        return this;
    }

    public ApiGetNodeResponseBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiGetNodeResponse.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetNodeResponse build() {
        return apiGetNodeResponse;
    }
}