/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiGetNodeSessionRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5760423315326323017L;
    private String devAddr;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("devAddr")
    public String getDevAddr ( ) { 
        return this.devAddr;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("devAddr")
    public void setDevAddr (String value) { 
        this.devAddr = value;
    }
 
}
 