/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetNodeSessionResponseBuilder {
    //the instance to build
    private ApiGetNodeSessionResponse apiGetNodeSessionResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetNodeSessionResponseBuilder() {
        apiGetNodeSessionResponse = new ApiGetNodeSessionResponse();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiGetNodeSessionResponseBuilder appEUI(String appEUI) {
        apiGetNodeSessionResponse.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppSKey
     */
    public ApiGetNodeSessionResponseBuilder appSKey(String appSKey) {
        apiGetNodeSessionResponse.setAppSKey(appSKey);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder cFList(List<Integer> cFList) {
        apiGetNodeSessionResponse.setCFList(cFList);
        return this;
    }

    /**
     * hex encoded DevAddr
     */
    public ApiGetNodeSessionResponseBuilder devAddr(String devAddr) {
        apiGetNodeSessionResponse.setDevAddr(devAddr);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiGetNodeSessionResponseBuilder devEUI(String devEUI) {
        apiGetNodeSessionResponse.setDevEUI(devEUI);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder fCntDown(Integer fCntDown) {
        apiGetNodeSessionResponse.setFCntDown(fCntDown);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder fCntUp(Integer fCntUp) {
        apiGetNodeSessionResponse.setFCntUp(fCntUp);
        return this;
    }

    /**
     * hex encoded NwkSKey
     */
    public ApiGetNodeSessionResponseBuilder nwkSKey(String nwkSKey) {
        apiGetNodeSessionResponse.setNwkSKey(nwkSKey);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder rx1DROffset(Integer rx1DROffset) {
        apiGetNodeSessionResponse.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder rx2DR(Integer rx2DR) {
        apiGetNodeSessionResponse.setRx2DR(rx2DR);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder rxDelay(Integer rxDelay) {
        apiGetNodeSessionResponse.setRxDelay(rxDelay);
        return this;
    }

    public ApiGetNodeSessionResponseBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiGetNodeSessionResponse.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetNodeSessionResponse build() {
        return apiGetNodeSessionResponse;
    }
}