/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetChannelListRequestBuilder {
    //the instance to build
    private ApiGetChannelListRequest apiGetChannelListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetChannelListRequestBuilder() {
        apiGetChannelListRequest = new ApiGetChannelListRequest();
    }

    public ApiGetChannelListRequestBuilder id(String id) {
        apiGetChannelListRequest.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetChannelListRequest build() {
        return apiGetChannelListRequest;
    }
}