/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiGetChannelResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5372531693475408688L;
    private String channel;
    private String channelListID;
    private String frequency;
    private String id;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("channel")
    public String getChannel ( ) { 
        return this.channel;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("channel")
    public void setChannel (String value) { 
        this.channel = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("channelListID")
    public String getChannelListID ( ) { 
        return this.channelListID;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("channelListID")
    public void setChannelListID (String value) { 
        this.channelListID = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("frequency")
    public String getFrequency ( ) { 
        return this.frequency;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("frequency")
    public void setFrequency (String value) { 
        this.frequency = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("id")
    public String getId ( ) { 
        return this.id;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("id")
    public void setId (String value) { 
        this.id = value;
    }
 
}
 