/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetApplicationResponseBuilder {
    //the instance to build
    private ApiGetApplicationResponse apiGetApplicationResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetApplicationResponseBuilder() {
        apiGetApplicationResponse = new ApiGetApplicationResponse();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiGetApplicationResponseBuilder appEUI(String appEUI) {
        apiGetApplicationResponse.setAppEUI(appEUI);
        return this;
    }

    /**
     * name of the application
     */
    public ApiGetApplicationResponseBuilder name(String name) {
        apiGetApplicationResponse.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetApplicationResponse build() {
        return apiGetApplicationResponse;
    }
}