/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetNodeRequestBuilder {
    //the instance to build
    private ApiGetNodeRequest apiGetNodeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetNodeRequestBuilder() {
        apiGetNodeRequest = new ApiGetNodeRequest();
    }

    /**
     * hex encoded DevEUI
     */
    public ApiGetNodeRequestBuilder devEUI(String devEUI) {
        apiGetNodeRequest.setDevEUI(devEUI);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetNodeRequest build() {
        return apiGetNodeRequest;
    }
}