/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiGetNodeSessionRequestBuilder {
    //the instance to build
    private ApiGetNodeSessionRequest apiGetNodeSessionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiGetNodeSessionRequestBuilder() {
        apiGetNodeSessionRequest = new ApiGetNodeSessionRequest();
    }

    public ApiGetNodeSessionRequestBuilder devAddr(String devAddr) {
        apiGetNodeSessionRequest.setDevAddr(devAddr);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiGetNodeSessionRequest build() {
        return apiGetNodeSessionRequest;
    }
}