/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListApplicationRequestBuilder {
    //the instance to build
    private ApiListApplicationRequest apiListApplicationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListApplicationRequestBuilder() {
        apiListApplicationRequest = new ApiListApplicationRequest();
    }

    /**
     * max number of results to return
     */
    public ApiListApplicationRequestBuilder limit(String limit) {
        apiListApplicationRequest.setLimit(limit);
        return this;
    }

    /**
     * result offset (for pagination)
     */
    public ApiListApplicationRequestBuilder offset(String offset) {
        apiListApplicationRequest.setOffset(offset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListApplicationRequest build() {
        return apiListApplicationRequest;
    }
}