/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListChannelListResponseBuilder {
    //the instance to build
    private ApiListChannelListResponse apiListChannelListResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListChannelListResponseBuilder() {
        apiListChannelListResponse = new ApiListChannelListResponse();
    }

    public ApiListChannelListResponseBuilder result(List<ApiGetChannelListResponse> result) {
        apiListChannelListResponse.setResult(result);
        return this;
    }

    public ApiListChannelListResponseBuilder totalCount(String totalCount) {
        apiListChannelListResponse.setTotalCount(totalCount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListChannelListResponse build() {
        return apiListChannelListResponse;
    }
}