/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListNodeResponseBuilder {
    //the instance to build
    private ApiListNodeResponse apiListNodeResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListNodeResponseBuilder() {
        apiListNodeResponse = new ApiListNodeResponse();
    }

    public ApiListNodeResponseBuilder result(List<ApiGetNodeResponse> result) {
        apiListNodeResponse.setResult(result);
        return this;
    }

    public ApiListNodeResponseBuilder totalCount(String totalCount) {
        apiListNodeResponse.setTotalCount(totalCount);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListNodeResponse build() {
        return apiListNodeResponse;
    }
}