/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListNodeByAppEUIRequestBuilder {
    //the instance to build
    private ApiListNodeByAppEUIRequest apiListNodeByAppEUIRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListNodeByAppEUIRequestBuilder() {
        apiListNodeByAppEUIRequest = new ApiListNodeByAppEUIRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiListNodeByAppEUIRequestBuilder appEUI(String appEUI) {
        apiListNodeByAppEUIRequest.setAppEUI(appEUI);
        return this;
    }

    public ApiListNodeByAppEUIRequestBuilder limit(String limit) {
        apiListNodeByAppEUIRequest.setLimit(limit);
        return this;
    }

    public ApiListNodeByAppEUIRequestBuilder offset(String offset) {
        apiListNodeByAppEUIRequest.setOffset(offset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListNodeByAppEUIRequest build() {
        return apiListNodeByAppEUIRequest;
    }
}