/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListChannelListRequestBuilder {
    //the instance to build
    private ApiListChannelListRequest apiListChannelListRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListChannelListRequestBuilder() {
        apiListChannelListRequest = new ApiListChannelListRequest();
    }

    public ApiListChannelListRequestBuilder limit(String limit) {
        apiListChannelListRequest.setLimit(limit);
        return this;
    }

    public ApiListChannelListRequestBuilder offset(String offset) {
        apiListChannelListRequest.setOffset(offset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListChannelListRequest build() {
        return apiListChannelListRequest;
    }
}