/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiListNodeResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5605915257103868972L;
    private List<ApiGetNodeResponse> result;
    private String totalCount;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public List<ApiGetNodeResponse> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (List<ApiGetNodeResponse> value) { 
        this.result = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("totalCount")
    public String getTotalCount ( ) { 
        return this.totalCount;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("totalCount")
    public void setTotalCount (String value) { 
        this.totalCount = value;
    }
 
}
 