/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiListChannelsByChannelListResponse 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5577546721533858053L;
    private List<ApiGetChannelResponse> result;
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("result")
    public List<ApiGetChannelResponse> getResult ( ) { 
        return this.result;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("result")
    public void setResult (List<ApiGetChannelResponse> value) { 
        this.result = value;
    }
 
}
 