/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListChannelsByChannelListResponseBuilder {
    //the instance to build
    private ApiListChannelsByChannelListResponse apiListChannelsByChannelListResponse;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListChannelsByChannelListResponseBuilder() {
        apiListChannelsByChannelListResponse = new ApiListChannelsByChannelListResponse();
    }

    public ApiListChannelsByChannelListResponseBuilder result(List<ApiGetChannelResponse> result) {
        apiListChannelsByChannelListResponse.setResult(result);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListChannelsByChannelListResponse build() {
        return apiListChannelsByChannelListResponse;
    }
}