/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiListNodeRequestBuilder {
    //the instance to build
    private ApiListNodeRequest apiListNodeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiListNodeRequestBuilder() {
        apiListNodeRequest = new ApiListNodeRequest();
    }

    public ApiListNodeRequestBuilder limit(String limit) {
        apiListNodeRequest.setLimit(limit);
        return this;
    }

    public ApiListNodeRequestBuilder offset(String offset) {
        apiListNodeRequest.setOffset(offset);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiListNodeRequest build() {
        return apiListNodeRequest;
    }
}