/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;
import com.fasterxml.jackson.annotation.JsonGetter;
import com.fasterxml.jackson.annotation.JsonSetter;

public class ApiListNodeByAppEUIRequest 
        implements java.io.Serializable {
    private static final long serialVersionUID = 5011700102746351230L;
    private String appEUI;
    private String limit;
    private String offset;
    /** GETTER
     * hex encoded AppEUI
     */
    @JsonGetter("appEUI")
    public String getAppEUI ( ) { 
        return this.appEUI;
    }
    
    /** SETTER
     * hex encoded AppEUI
     */
    @JsonSetter("appEUI")
    public void setAppEUI (String value) { 
        this.appEUI = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("limit")
    public String getLimit ( ) { 
        return this.limit;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("limit")
    public void setLimit (String value) { 
        this.limit = value;
    }
 
    /** GETTER
     * TODO: Write general description for this method
     */
    @JsonGetter("offset")
    public String getOffset ( ) { 
        return this.offset;
    }
    
    /** SETTER
     * TODO: Write general description for this method
     */
    @JsonSetter("offset")
    public void setOffset (String value) { 
        this.offset = value;
    }
 
}
 