/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiUpdateNodeSessionRequestBuilder {
    //the instance to build
    private ApiUpdateNodeSessionRequest apiUpdateNodeSessionRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiUpdateNodeSessionRequestBuilder() {
        apiUpdateNodeSessionRequest = new ApiUpdateNodeSessionRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiUpdateNodeSessionRequestBuilder appEUI(String appEUI) {
        apiUpdateNodeSessionRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppSKey
     */
    public ApiUpdateNodeSessionRequestBuilder appSKey(String appSKey) {
        apiUpdateNodeSessionRequest.setAppSKey(appSKey);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder cFList(List<Integer> cFList) {
        apiUpdateNodeSessionRequest.setCFList(cFList);
        return this;
    }

    /**
     * hex encoded DevAddr
     */
    public ApiUpdateNodeSessionRequestBuilder devAddr(String devAddr) {
        apiUpdateNodeSessionRequest.setDevAddr(devAddr);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiUpdateNodeSessionRequestBuilder devEUI(String devEUI) {
        apiUpdateNodeSessionRequest.setDevEUI(devEUI);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder fCntDown(Integer fCntDown) {
        apiUpdateNodeSessionRequest.setFCntDown(fCntDown);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder fCntUp(Integer fCntUp) {
        apiUpdateNodeSessionRequest.setFCntUp(fCntUp);
        return this;
    }

    /**
     * hex encoded NwkSKey
     */
    public ApiUpdateNodeSessionRequestBuilder nwkSKey(String nwkSKey) {
        apiUpdateNodeSessionRequest.setNwkSKey(nwkSKey);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder rx1DROffset(Integer rx1DROffset) {
        apiUpdateNodeSessionRequest.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder rx2DR(Integer rx2DR) {
        apiUpdateNodeSessionRequest.setRx2DR(rx2DR);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder rxDelay(Integer rxDelay) {
        apiUpdateNodeSessionRequest.setRxDelay(rxDelay);
        return this;
    }

    public ApiUpdateNodeSessionRequestBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiUpdateNodeSessionRequest.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiUpdateNodeSessionRequest build() {
        return apiUpdateNodeSessionRequest;
    }
}