/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiUpdateChannelRequestBuilder {
    //the instance to build
    private ApiUpdateChannelRequest apiUpdateChannelRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiUpdateChannelRequestBuilder() {
        apiUpdateChannelRequest = new ApiUpdateChannelRequest();
    }

    public ApiUpdateChannelRequestBuilder channel(String channel) {
        apiUpdateChannelRequest.setChannel(channel);
        return this;
    }

    public ApiUpdateChannelRequestBuilder channelListID(String channelListID) {
        apiUpdateChannelRequest.setChannelListID(channelListID);
        return this;
    }

    public ApiUpdateChannelRequestBuilder frequency(String frequency) {
        apiUpdateChannelRequest.setFrequency(frequency);
        return this;
    }

    public ApiUpdateChannelRequestBuilder id(String id) {
        apiUpdateChannelRequest.setId(id);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiUpdateChannelRequest build() {
        return apiUpdateChannelRequest;
    }
}