/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiUpdateNodeRequestBuilder {
    //the instance to build
    private ApiUpdateNodeRequest apiUpdateNodeRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiUpdateNodeRequestBuilder() {
        apiUpdateNodeRequest = new ApiUpdateNodeRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiUpdateNodeRequestBuilder appEUI(String appEUI) {
        apiUpdateNodeRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * hex encoded AppKey
     */
    public ApiUpdateNodeRequestBuilder appKey(String appKey) {
        apiUpdateNodeRequest.setAppKey(appKey);
        return this;
    }

    public ApiUpdateNodeRequestBuilder channelListID(String channelListID) {
        apiUpdateNodeRequest.setChannelListID(channelListID);
        return this;
    }

    /**
     * hex encoded DevEUI
     */
    public ApiUpdateNodeRequestBuilder devEUI(String devEUI) {
        apiUpdateNodeRequest.setDevEUI(devEUI);
        return this;
    }

    public ApiUpdateNodeRequestBuilder rx1DROffset(Integer rx1DROffset) {
        apiUpdateNodeRequest.setRx1DROffset(rx1DROffset);
        return this;
    }

    public ApiUpdateNodeRequestBuilder rx2DR(Integer rx2DR) {
        apiUpdateNodeRequest.setRx2DR(rx2DR);
        return this;
    }

    public ApiUpdateNodeRequestBuilder rxDelay(Integer rxDelay) {
        apiUpdateNodeRequest.setRxDelay(rxDelay);
        return this;
    }

    public ApiUpdateNodeRequestBuilder rxWindow(ApiRXWindowEnum rxWindow) {
        apiUpdateNodeRequest.setRxWindow(rxWindow);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiUpdateNodeRequest build() {
        return apiUpdateNodeRequest;
    }
}