/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example.models;

import java.util.*;

public class ApiUpdateApplicationRequestBuilder {
    //the instance to build
    private ApiUpdateApplicationRequest apiUpdateApplicationRequest;

    /**
     * Default constructor to initialize the instance
     */
    public ApiUpdateApplicationRequestBuilder() {
        apiUpdateApplicationRequest = new ApiUpdateApplicationRequest();
    }

    /**
     * hex encoded AppEUI
     */
    public ApiUpdateApplicationRequestBuilder appEUI(String appEUI) {
        apiUpdateApplicationRequest.setAppEUI(appEUI);
        return this;
    }

    /**
     * name of the application
     */
    public ApiUpdateApplicationRequestBuilder name(String name) {
        apiUpdateApplicationRequest.setName(name);
        return this;
    }
    /**
     * Build the instance with the given values
     */
    public ApiUpdateApplicationRequest build() {
        return apiUpdateApplicationRequest;
    }
}