/*
 * LoRaServerRESTAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ).
 */
package com.example;


public class Configuration {
    //The base Uri for API calls
    public static String baseUri = "http://example.com/api";

}
